# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-12 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='supervisors',
            field=models.ManyToManyField(related_name='supervisors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportresponse',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reports.Report'),
        ),
    ]
